"use client";

import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, CheckCircle2 } from "lucide-react";
import { processStages } from "@/content/process";

export function ProcessExperience() {
  const reduceMotion = useReducedMotion();
  return <>
    <section className="relative overflow-hidden bg-ink pb-20 pt-36 text-ink-foreground md:pb-28 md:pt-44" data-header-tone="dark">
      <motion.div aria-hidden="true" className="absolute -right-[20%] top-0 h-[34rem] w-[34rem] rounded-full bg-accent/25 blur-3xl" animate={reduceMotion ? undefined : { x: [0, -100, 0], y: [0, 80, 0], scale: [1, 1.2, 1] }} transition={{ duration: 14, repeat: Infinity, ease: "easeInOut" }} />
      <div className="pointer-events-none absolute inset-0 opacity-20 [background-image:linear-gradient(90deg,rgba(255,255,255,.14)_1px,transparent_1px),linear-gradient(rgba(255,255,255,.14)_1px,transparent_1px)] [background-size:4rem_4rem]" />
      <div className="container-page relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-accent">Process / a continuous build</p><h1 className="mt-5 max-w-4xl text-balance font-display text-4xl font-medium leading-[1.03] md:text-6xl">From a first signal to a living product.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-ink-muted">A transparent seven-part journey, with a deliberate handoff at every stage.</p></div><motion.div className="hidden size-32 items-center justify-center rounded-full border border-white/20 lg:flex" animate={reduceMotion ? undefined : { rotate: 360 }} transition={{ duration: 18, repeat: Infinity, ease: "linear" }}><ArrowDown className="size-7 text-accent" /></motion.div></div>
    </section>
    <section className="relative py-16 md:py-28"><div className="container-page relative"><div aria-hidden="true" className="absolute bottom-0 left-[2.1rem] top-0 hidden w-px bg-border md:block" /><motion.div aria-hidden="true" className="absolute left-[2.1rem] top-0 hidden h-32 w-px origin-top bg-accent md:block" whileInView={reduceMotion ? undefined : { scaleY: [0, 1] }} transition={{ duration: 1.1, ease: [0.16, 1, 0.3, 1] }} viewport={{ once: true }} /><div className="space-y-5 md:space-y-8">
      {processStages.map((stage, index) => <motion.article key={stage.number} className="relative grid gap-5 rounded-3xl border border-border bg-card p-6 md:grid-cols-[4.5rem_1.1fr_1fr_1fr] md:gap-8 md:p-9" initial={reduceMotion ? false : { opacity: 0, x: index % 2 ? 64 : -64, rotate: index % 2 ? 1.5 : -1.5 }} whileInView={{ opacity: 1, x: 0, rotate: 0 }} viewport={{ once: true, amount: 0.22 }} transition={{ duration: 0.72, delay: index * 0.04, ease: [0.16, 1, 0.3, 1] }} whileHover={reduceMotion ? undefined : { scale: 1.012, transition: { duration: 0.25 } }}><div className="relative z-10 flex items-start gap-4 md:block"><span className="grid size-11 place-items-center rounded-full bg-ink font-display text-lg text-white">{stage.number}</span><span className="pt-2 text-xs font-semibold uppercase tracking-[0.18em] text-accent md:hidden">Stage</span></div><div><h2 className="font-display text-2xl font-medium">{stage.title}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{stage.whatHappens}</p></div><div className="border-t border-border pt-4 md:border-l md:border-t-0 md:pl-7 md:pt-0"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">You receive</p><p className="mt-3 text-sm leading-relaxed">{stage.whatClientReceives}</p></div><div className="border-t border-border pt-4 md:border-l md:border-t-0 md:pl-7 md:pt-0"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Then</p><p className="mt-3 flex gap-2 text-sm leading-relaxed"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-accent" />{stage.whatsNext}</p></div></motion.article>)}
    </div></div></section>
  </>;
}
